import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import DarkMode from './DarkMode'
import { cookies } from 'next/headers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  let cookie = cookies().get('mode')
  return (
    <html lang="en">
      <body
        className={
          cookie != undefined && cookie.value == 'dark' ? 'dark-mode' : ''
        }
      >
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <LoginBtn></LoginBtn>
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  )
}
